"""Agent-related models for runs, insights, actions, and creatives."""

from sqlalchemy import Column, String, Integer, Text, ForeignKey, DateTime, Numeric
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import uuid
from app.database import Base


class AgentRun(Base):
    """Agent execution run tracking."""

    __tablename__ = "agent_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    run_type = Column(String(50), nullable=False, index=True)  # 'weekly', 'daily', 'ad_hoc'
    status = Column(String(50), nullable=False, index=True)  # 'running', 'completed', 'failed'
    started_at = Column(DateTime(timezone=True), server_default=func.now())
    completed_at = Column(DateTime(timezone=True))
    input_params = Column(JSONB)
    output = Column(JSONB)
    error_message = Column(Text)

    # Relationships
    insights = relationship("Insight", back_populates="agent_run", cascade="all, delete-orphan")
    actions = relationship("Action", back_populates="agent_run", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<AgentRun(id={self.id}, run_type='{self.run_type}', status='{self.status}')>"


class Insight(Base):
    """Insights generated by Analytics Agent."""

    __tablename__ = "insights"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_run_id = Column(UUID(as_uuid=True), ForeignKey("agent_runs.id"), nullable=False, index=True)
    insight_type = Column(String(50), nullable=False)  # 'drop', 'spike', 'opportunity', 'anomaly'
    campaign_id = Column(UUID(as_uuid=True), ForeignKey("campaigns.id"), nullable=False, index=True)
    metric = Column(String(50), nullable=False)
    change_percent = Column(Numeric(10, 2))
    description = Column(Text)
    severity = Column(String(20))  # 'low', 'medium', 'high', 'critical'
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    agent_run = relationship("AgentRun", back_populates="insights")
    campaign = relationship("Campaign", backref="insights")

    def __repr__(self):
        return f"<Insight(type='{self.insight_type}', metric='{self.metric}', severity='{self.severity}')>"


class Action(Base):
    """Actions recommended by Strategist Agent."""

    __tablename__ = "actions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_run_id = Column(UUID(as_uuid=True), ForeignKey("agent_runs.id"), nullable=False, index=True)
    action_type = Column(String(50), nullable=False)  # 'scale', 'pause', 'test', 'fix', 'optimize'
    campaign_id = Column(UUID(as_uuid=True), ForeignKey("campaigns.id"), nullable=True, index=True)
    description = Column(Text)
    priority = Column(String(20))  # 'low', 'medium', 'high'
    status = Column(String(50), default="pending", index=True)  # 'pending', 'approved', 'rejected', 'executed'
    approved_by = Column(String(255))
    approved_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    agent_run = relationship("AgentRun", back_populates="actions")
    campaign = relationship("Campaign", backref="actions")
    creatives = relationship("Creative", back_populates="action", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Action(type='{self.action_type}', status='{self.status}', priority='{self.priority}')>"


class Creative(Base):
    """Creative content generated by Content Agent."""

    __tablename__ = "creatives"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_run_id = Column(UUID(as_uuid=True), ForeignKey("agent_runs.id"), nullable=False, index=True)
    action_id = Column(UUID(as_uuid=True), ForeignKey("actions.id"), nullable=True, index=True)
    platform = Column(String(50), nullable=False)  # 'meta', 'google', etc.
    creative_type = Column(String(50))  # 'ad_copy', 'image_ad', 'video_ad'
    headline = Column(Text)
    primary_text = Column(Text)
    description = Column(Text)
    call_to_action = Column(String(100))
    status = Column(String(50), default="draft", index=True)  # 'draft', 'approved', 'rejected', 'published'
    approved_by = Column(String(255))
    approved_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    agent_run = relationship("AgentRun", backref="creatives")
    action = relationship("Action", back_populates="creatives")

    def __repr__(self):
        return f"<Creative(platform='{self.platform}', status='{self.status}')>"



